/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

//package bookmybook; 
import javax.swing.table.*;
import java.sql.*;
import com.mysql.jdbc.Driver;
import java.util.*;

/**
 *
 * @author darshan-ubuntu
 */
public class orderDetails extends javax.swing.JFrame {

    BookMyBook parent;
    TableColumn column = null;
    TableModel model = null;
    ResultSet resultSet = null;
    Connection con = null;
    Statement statement;
    int[] quantity;
    int[] order_no;
    float[] price;
    int count;
    int cart_no;
    String[] title;
    String[] arr = null; 
    String em;
    
    /**
     * Creates new form orderDetails
     */
    public orderDetails(BookMyBook temp) {
        initComponents();
        parent = temp;
        cart_no = parent.cart_no;
                
        try {
            new Driver();

            con = DriverManager.getConnection(
                           "jdbc:mysql://localhost:3306/bookmybook?zeroDateTimeBehavior=convertToNull",
                           "root",
                           "sankafc");

            statement = con.createStatement();

            resultSet = statement
                    .executeQuery("select count(*) from BOOK B, ORDERS O where O.isbn=B.isbn and cart_no='" + cart_no + "';");
            
            while (resultSet.next()) {
                count = resultSet.getInt(1);
                System.out.println("Count = " + count);
            }
            
            order_no = new int[count];
            quantity = new int[count];
            price = new float[count];
            title = new String[count];

            resultSet = statement
                    .executeQuery("select O.order_no, O.order_qty, B.title, B.price from BOOK B, ORDERS O where O.isbn=B.isbn and cart_no='" + cart_no + "';");
            
            int i=1;

            while (resultSet.next()) {
 
                System.out.println("i=" + i);

                em = resultSet.getString("order_no");
                arr = em.split("\n");
                order_no[i-1] = Integer.parseInt(arr[0]);

                em = resultSet.getString("title");
                arr = em.split("\n");
                title[i-1] = arr[0];

                em = resultSet.getString("order_qty");
                arr = em.split("\n");
                quantity[i-1] = Integer.parseInt(arr[0]);
                
                em = resultSet.getString("price");
                arr = em.split("\n");
                price[i-1] = Float.parseFloat(arr[0]);
                
                i++;

            }
            
            for(int l=0;l<count;l++) {
                System.out.println("Order_no = " + order_no[l]);
                jTable1.getModel().setValueAt(order_no[l], l, 0);
            }

            for(int l=0;l<count;l++) {
                System.out.println("Title = " + title[l]);
                jTable1.getModel().setValueAt(title[l], l, 1);
            }

            for(int l=0;l<count;l++) {
                System.out.println("Quantity = " + quantity[l]);
                jTable1.getModel().setValueAt(quantity[l], l, 2);
            }

            for(int l=0;l<count;l++) {
                System.out.println("Price = " + price[l]);
                jTable1.getModel().setValueAt(price[l], l, 3);
            }

        }
        
        catch (SQLException e) {
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("List of Orders");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order Number", "Book Title", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jButton1.setText("Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton3)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int numRows = jTable1.getSelectedRow();

        model = jTable1.getModel();
        
        String temp = jTable1.getModel().getValueAt(numRows, 0).toString();
        System.out.println(temp);
        
        for (int i=0;i<4;i++){
            
            jTable1.getModel().setValueAt(null, numRows, i);
            
        }
        
        String query = "delete from ORDERS where cart_no='" + cart_no + "' and order_no='" + Integer.parseInt(temp) + "';";
        try {
                statement.execute(query);
        }
        catch(SQLException e) {
                e.printStackTrace();
        }

        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        parent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        payment y = new payment(this);
        y.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
