/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 *///package bookmybook;

import java.sql.*;
import com.mysql.jdbc.Driver;
import java.util.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.WindowConstants;
import java.util.Date;
import java.util.Calendar.*;
/**
 *
 * @author darshan-ubuntu
 */
public class titleSearch extends javax.swing.JFrame {

    private Connection con = null;
    private Statement statement = null;
    ResultSet resultSet = null;
    String bookName;
    Vector titleList;
    String selected = "";
    BookMyBook parent;
    String uname;
    PreparedStatement preparedStatement = null;
    String isbn;
    int cart_no;
    String date;
    int order_no;
    int quantity;
    int stock_qty;
    
    /**
     * Creates new form titleSearch
     */
    public titleSearch(BookMyBook temp,String uname) throws SQLException {
        initComponents();
        
        bookName = new String();
        titleList = new Vector();
        parent = temp;
        this.uname = uname;
        cart_no = parent.cart_no;
        order_no = parent.order_no;
        
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent ev) {
                parent.setVisible(true);
                parent.order_no = order_no;
                parent.cart_no = cart_no;
            }
        });

        new Driver();
       
        con = DriverManager.getConnection(
                       "jdbc:mysql://localhost:3306/bookmybook?zeroDateTimeBehavior=convertToNull",
                       "root",
                       "sankafc");
        
        statement = con.createStatement();
        
        jList1.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent evt) {
                if (!evt.getValueIsAdjusting()) {
                    // code here
                    selected = jList1.getSelectedValue().toString();
                    System.out.println("SELECTED"+selected);
                }
            }
        });
        
        fillList();
    }
    
    void fillList() {
        try {
            resultSet = statement
                .executeQuery("select title from BOOK;");
   
            while (resultSet.next()) {
                titleList.addElement(resultSet.getString("title"));
            }
            jList1.setListData( titleList );
        }
        catch (SQLException e) {
            e.printStackTrace();
        }
                
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("List of Books");

        jScrollPane1.setViewportView(jList1);

        jButton3.setText("Select");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter Quantity :");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(selected.equals("")){
            JOptionPane.showMessageDialog(null, "Please select a book");
        }
        else if(jTextField1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter quantity");
        }
        else if(uname.equals("")){
            JOptionPane.showMessageDialog(null, "You need to login to place an order");
        }
        else {
            Date d = new Date();
            SimpleDateFormat df = new SimpleDateFormat( "yyyy");
            date = df.format(d) + "-";
            df = new SimpleDateFormat( "MM");
            date = date + df.format(d) + "-";
            df = new SimpleDateFormat( "dd");
            date = date + df.format(d);

            quantity = Integer.parseInt(jTextField1.getText());
            System.out.println(quantity);

            try {
                if (cart_no == 0) {
                    resultSet = statement
                        .executeQuery("select max(cart_no) from CART;");
                    if (resultSet.next()) {
                        cart_no = resultSet.getInt(1) + 1;
                        System.out.println("cart_no=" + cart_no);
                    }
                    else {
                        cart_no = 1;
                    }
                }
                
                if (order_no == 0) {
                    resultSet = statement
                        .executeQuery("select max(order_no) from ORDERS;");
                    if (resultSet.next()) {
                        order_no = resultSet.getInt(1) + 1;
                        System.out.println("order_no=" + order_no);
                    }
                    else {
                        order_no = 1;
                    }
                }
                else {
                    order_no++;
                }

            }
            catch (SQLException e) {
                e.printStackTrace();
            }

            try {
                resultSet = statement
                        .executeQuery("select isbn from BOOK where title='" + selected + "';");

                while (resultSet.next()) {
                    isbn = resultSet.getString(1);
                    System.out.println("ISBN" + isbn);
                }
            }
            catch (SQLException e) {
                e.printStackTrace();
            }

                        try {
                    resultSet = statement
                            .executeQuery("select S.stock_qty from STOCK S, BOOK B where S.ISBN='"+ isbn + "';");

                    while (resultSet.next()) {
                        stock_qty = resultSet.getInt(1);
                    }
            }
            catch (SQLException e) {
                    e.printStackTrace();
            }
            
            System.out.println("Stock qty = " + stock_qty);
            
            if (stock_qty < quantity) {
                    JOptionPane.showMessageDialog(null, "Stock not available for selected quantity. Available quantity is " + stock_qty);
            }
            
            else {

                try {
                    preparedStatement = con
                            .prepareStatement("insert into CART values (" + cart_no + ",'" + uname + "');");
                    System.out.println("insert into CART values (" + cart_no + ",'" + uname + "');");
                    preparedStatement.executeUpdate();
                }
                catch (SQLException e) {

                }

        //SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss"); 
        //time.setText(sdf.format(cal.getTime()));
                try {
                    preparedStatement = con
                            .prepareStatement("insert into ORDERS values (" + order_no + "," + cart_no + ",'" + isbn + "'," + quantity +",'2013-12-16');");
                    System.out.println ("insert into ORDERS values (" + order_no + "," + cart_no + ",'" + isbn + "'," + quantity +",'" + date + "');");
                    preparedStatement.executeUpdate();
                }
                catch (SQLException e) {
                    e.printStackTrace();
                }

                JOptionPane.showMessageDialog(null, "Book selected");
            }

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        parent.cart_no=cart_no;
        parent.order_no=order_no;
        parent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
